---
- hosts: loadbalancer
  vars_prompt:
          - name: fsp
            prompt: Please give the front server port number 
            private: no

          - name: bsp
            prompt: Please give the backend server port number 
            private: no   
  tasks:
          - name: Install the haproxy
            package:
              name: haproxy
              state: present
        

          - name: Change the config file of haproxy
            template:
              dest: /etc/haproxy/haproxy.cfg
              src: haproxy.cfg.j2
            notify:
              - Restart the service

          - name: Start the service 
            service:
               name: haproxy
               state: started
               enabled: yes


  handlers:
          - name: Restart the service
            service:
               name: haproxy
               state: restarted     

- hosts: Backend_servers
  tasks: 

          - name: Install the PHP
            package:
              name: php
              state: present

          - name: Configure Webserver
            package:
              name: httpd
              state: present
           
          - name: Copy the webpages 
            copy:
              dest: /var/www/html
              src: index.php

          - name: Start the httpd services
            service:
              name: httpd
              state: started



                      
                        
